---
services:
  vault:
    image: index.docker.io/hashicorp/vault-enterprise:1.19-ent
    environment:
      VAULT_LICENSE: ${VAULT_LICENSE}
      # VAULT_DEV_ROOT_TOKEN_ID: root
      # VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      # VAULT_LOCAL_CONFIG: |
      #   {
      #     "disable_mlock": true,
      #     "storage": {
      #       "raft": {
      #         "path": "/vault/file"
      #       }
      #     },
      #     "api_addr": "http://127.0.0.1:8200",
      #     "cluster_addr": "https://127.0.0.1:8201",
      #     "default_lease_ttl": "168h",
      #     "max_lease_ttl": "720h",
      #     "ui": true
      #   }
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - ./vault-config:/vault/config:ro
      - ./vault-data:/vault/file
      - ./logs:/var/log/vault:rw
    restart: always
    entrypoint: vault server -config=/vault/config/config.hcl
